### PR TITLE
feat: custom package.json location

### PR DESCRIPTION
**Pull request by esbakker**
### :pencil: Description
- Added an input for setting a custom location for the package.json to validate

### :link: Related Issues
- 

I wasn't sure how to add a unit test for this, since the package.json content seems to be passed as strings in the tests?

### CODE REVIEW

**Review by danadajian — APPROVED** [review]

**Comment by danadajian** [comment]
@esbakker Thanks for contributing! I think you'll need to run `bun run package` in order to get the `dist/` code to match what the CI generates.

**Comment by danadajian** [comment]
@esbakker It's still not matching. I think you might be able to add `github-actions[bot]` as a collaborator to your fork, and the CI will push the commit to your branch.

**Comment by esbakker** [comment]
@danadajian The rights for workflows seem to be correct. I ran the build workflow from my own repo and there it succeeded. I cherry picked the changes, so hopefully it will succeed now

**Review by danadajian — APPROVED** [review]

**Pull request merged**
